### ISSUE TITLE
Redis is disabled.

### ISSUE THREAD

**Issue by Adzkii** [Xon/XenForo-RedisCache#3]
I'm having an issue, on my ACP it says Redis is disabled. Also i checked for on my redis admin panel to see if xenforo is being cached by redis but no keys found. I have my config.php set up correctly as stated in the description. 
I'm running php 7 on ubuntu.

> $config['cache']['backend'] = 'Redis';
> $config['cache']['backendOptions'] = array(
> 'server' => '127.0.0.1',
> 'port' => 6379,
> 'connect_retries' => 2,
> 'use_lua' => true
> );
> require(XenForo_Application::getInstance()->getConfigDir().'/SV/RedisCache/Installer.php'
> );
> $config['cache']['frontendOptions']['automatic_serialization'] = false;

Cheers.

**Comment by Xon** [comment]
Please follow the XenForo caching setup, you need more configuration than that. 

Additionally, I only offer XenForo support on my personal site (for users with a valid Xenforo licence) or in the XenForo Forum in the customer only area.

**Comment by Adzkii** [comment]
I see no difference here or xenforo forum. I tried the cache configuration you put down in the description but that didn't work out. But thanks anyway!
